### ISSUE TITLE
VestingSchedulerV2 stuck on optimism-mainnet

### ISSUE THREAD

**Issue by d10r** [d10r/sf-scheduler-backend#2]
```
init: loaded state from file - lastBlock: 122170481, activeSchedules: 0, removedSchedules: 0
*** query for past events from 122170482 to 122220481 (of 126517324) returned 6 events
parsedEvent detail: {
  "name": "VestingScheduleDeleted",
  "superToken": "0x7d342726B69C28D942ad8BfE6Ac81b972349d524",
  "sender": "0xF9Ce34dFCD3cc92804772F3022AF27bCd5E43Ff2",
  "receiver": "0x4e1dfc95c49186c8D6fAf7a33064Cc74F6Af235D",
  "blockNumber": 122197816,
  "transactionHash": "0xfb6e67f67aedaad6a3fbb1575406b1b4551d94d4d00fea5080ca06cc69be0784"
}
DELETED: {
  "name": "VestingScheduleDeleted",
  "superToken": "0x7d342726B69C28D942ad8BfE6Ac81b972349d524",
  "sender": "0xF9Ce34dFCD3cc92804772F3022AF27bCd5E43Ff2",
  "receiver": "0x4e1dfc95c49186c8D6fAf7a33064Cc74F6Af235D",
  "blockNumber": 122197816,
  "transactionHash": "0xfb6e67f67aedaad6a3fbb1575406b1b4551d94d4d00fea5080ca06cc69be0784"
}
```

the state file is has no schedules.

First trying a resync.

**Comment by d10r** [comment]
The problem persists.

The transaction was 100 days ago, shortly after the contract was deployed: https://optimistic.etherscan.io/tx/0xfb6e67f67aedaad6a3fbb1575406b1b4551d94d4d00fea5080ca06cc69be0784
block 122197816

Unfortunately etherscan only shows the last 25 events of the contract: https://optimistic.etherscan.io/address/0xe567b32c10b0db72d9490eb1b9a409c5aded192c#events

tenderly seems to be incomplete too: https://dashboard.tenderly.co/contract/optimistic/0xe567b32c10b0db72d9490eb1b9a409c5aded192c/transactions?perPage=100

How do I get all events?

Blockscout to the rescue:
https://optimism.blockscout.com/address/0xe567b32C10B0dB72d9490eB1B9A409C5ADed192C?tab=logs&page=9&next_page_params=%257B%2522block_number%2522%253A122206317%252C%2522index%2522%253A27%252C%2522items_count%2522%253A400%257D

first tx: https://optimism.blockscout.com/tx/0x407a16c818417600f6a28ba0c8b5af2e7eaa80da88076e6eeb69ceaf3ab7e4bb
block 122197549

`VestingScheduleCreated` changed in v2.

Solution: with the refactoring selection of the correct abi was lost, fixed in https://github.com/d10r/sf-scheduler-backend/pull/1/commits/7734b3df70b790db183ac4201ddbb211f0d8c63f

**Comment by majidrazaee2** [comment]
با تشکر
